Metrics/AbcSize:
  Max: 18

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 110

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Naming/PredicateName:
  Exclude:
    - lib/watirsome/regions.rb

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
